"""empty message

Revision ID: 19edcc14d218
Revises: a806a74338a9
Create Date: 2024-01-03 00:44:56.032418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19edcc14d218'
down_revision = 'a806a74338a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_item', sa.Float(), nullable=True))
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('total_item')

    # ### end Alembic commands ###
