"""empty message

Revision ID: 37273be1146e
Revises: b3c9ef9f868d
Create Date: 2024-01-28 16:25:46.035963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37273be1146e'
down_revision = 'b3c9ef9f868d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
