"""empty message

Revision ID: 9853ee218646
Revises: f5fb6d4d3be4
Create Date: 2024-03-24 20:34:25.274835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9853ee218646'
down_revision = 'f5fb6d4d3be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
